package entidades;
// Generated 14/07/2019 08:40:33 PM by Hibernate Tools 4.3.1



/**
 * TipoDocumento generated by hbm2java
 */
public class TipoDocumento  implements java.io.Serializable {


     private int codigo;
     private String tipoDocumento;
     private String descripcion;

    public TipoDocumento() {
    }

    public TipoDocumento(int codigo, String tipoDocumento, String descripcion) {
       this.codigo = codigo;
       this.tipoDocumento = tipoDocumento;
       this.descripcion = descripcion;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


